editor:
  render-on-save: true

project:
  type: website
  preview:
    port: 3000
    browser: false
    watch-inputs: true


website:
  title: "Theories of Quantum Matter"
  favicon: favicon-32x32.png
  page-navigation: true
  sidebar:
    # contents: auto
    collapse-level: -1
    style: floating
    contents:
      - index.qmd
      - section: "Notes"
        contents:
          - notes/intro.qmd
          - notes/many-body-wavefunctions.qmd
          - notes/quantum-hall-effect.qmd
          - notes/elastic-chain.qmd
          - notes/spin-models.qmd
          - notes/second-quantization.qmd
          - notes/more-second-quantization.qmd
          - notes/lattice-models.qmd
          - notes/bose-gas.qmd

      - section: "Slides"
        contents:
          - slides/many-body-wavefunctions.qmd
          - slides/quantum-hall-effect.qmd
          - slides/elastic-chain.qmd
          - slides/spin-models.qmd
          - slides/second-quantization.qmd
          - slides/more-second-quantization.qmd
          - slides/lattice-models.qmd
          

      - section: "Problem Sets"
        contents:
          - problem-sets/problem-set-1.qmd
          - problem-sets/problem-set-2.qmd

      - past-papers.qmd

bibliography: references.bib
number-sections: true

format:
  html:
    theme: cosmo
    toc: true
  # pdf:
  #   documentclass: scrbook
  #   papersize: a4

execute:
  freeze: auto  # re-render only when source changes


