# TQM Lectures 2024 {.unnumbered}

::: {.callout-warning appearance="minimal"}

Please complete the [feedback survey](https://cambridge.eu.qualtrics.com/jfe/form/SV_0diLIYDRbcAZSaq). Closes 1st December at midnight.

:::

::: {.callout-warning appearance="minimal"}

Check out these [Summer internships](assets/SummerInternship_25_Anzeige.pdf) at [MPIPKS, Dresden](https://www.pks.mpg.de/). Deadline for applications is 30th November!

:::

These are the materials for Theories of Quantum Matter, a Part III Physics course at the University of Cambridge taught in Michaelmas 2024. The materials for previous versions of the course can be found [here](https://austen.uk/courses/). While these are largely unchanged, you should regard this site as the authoritative version for 2024.

The source of these notes is [this GitHub repo](https://github.com/AustenLamacraft/tqm-quarto). If you find a typo, other problem or have any other comment on the material, please [raise an issue](https://github.com/AustenLamacraft/tqm-quarto/issues) there.

[The discussions section](https://github.com/AustenLamacraft/tqm-quarto/discussions/) is a good place to ask each other questions. Try it!

If you ever want access to the  for the mathematical expressions, right click and select `Show Math As` > `TeX Commands`.


::: {.callout-tip}
## Check

These "Check" boxes provide small exercises to check your understanding as you read the notes. Make sure you do them!

:::

::: {.callout-note}

"Note" boxes provide extra context that you may find interesting but aren't essential. Except this one. This one's important.

:::

Finally...

::: {.callout-warning}

In this course $\hbar = 1$!

:::

## Lectures {.unnumbered}

Take place in the Small Lecture Theatre at the Cavendish Laboratory from 09.30-11.00 on Tuesdays and Thursdays.

## Supervisions {.unnumbered}

There will be four supervisions, taking place in the weeks commencing 22/10, 5/11, 19/11, and 3/12.


